import java.time.LocalDate
import java.util.Properties

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("org.jetbrains.kotlin.plugin.compose")
}

// --- Auto-incrementing version: "YYYY-MM-DDx" where x = a, b, c... for
// successive builds on the same day. Forces Android's package manager to treat
// each installed APK as a genuine update (a static versionCode can make
// reinstalls silently no-op — see project memory 2026-06-07). State persisted
// in version.properties so the suffix survives across Gradle invocations.
val versionPropsFile = file("version.properties")
val todayIso = LocalDate.now().toString()                // e.g. "2026-06-07"
val todayCompact = todayIso.replace("-", "").toInt()     // e.g. 20260607

val versionProps = Properties().apply {
    if (versionPropsFile.exists()) versionPropsFile.inputStream().use { load(it) }
}
val storedDate = versionProps.getProperty("date")
val storedLetterIndex = versionProps.getProperty("letter")?.toIntOrNull() ?: -1

// Only consume a new letter when actually producing an installable artifact —
// not on every IDE sync / lint / test invocation.
val isBuildingArtifact = gradle.startParameter.taskNames.any { name ->
    listOf("assemble", "bundle", "install").any { name.contains(it, ignoreCase = true) }
}

val letterIndex = when {
    isBuildingArtifact && storedDate == todayIso -> storedLetterIndex + 1
    isBuildingArtifact                           -> 0
    storedDate == todayIso                        -> storedLetterIndex.coerceAtLeast(0)
    else                                          -> 0
}

if (isBuildingArtifact) {
    versionProps.setProperty("date", todayIso)
    versionProps.setProperty("letter", letterIndex.toString())
    versionPropsFile.outputStream().use {
        versionProps.store(it, "Auto-generated by app/build.gradle.kts — version letter counter, do not edit by hand")
    }
}

// Spreadsheet-column-style suffix: 0=a, 1=b, ..., 25=z, 26=aa, 27=ab, ...
fun letterSuffix(index: Int): String {
    var i = index
    val sb = StringBuilder()
    do { sb.insert(0, 'a' + i % 26); i = i / 26 - 1 } while (i >= 0)
    return sb.toString()
}

val computedVersionName = "$todayIso${letterSuffix(letterIndex)}"
val computedVersionCode = todayCompact * 100 + (letterIndex + 1)

android {
    namespace = "com.writhdeck.app"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.writhdeck.app"
        minSdk = 26
        targetSdk = 35
        versionCode = computedVersionCode
        versionName = computedVersionName
    }

    buildTypes {
        debug {
            applicationVariants.all {
                outputs.all {
                    (this as? com.android.build.gradle.internal.api.BaseVariantOutputImpl)
                        ?.outputFileName = "writhdeck-debug.apk"
                }
            }
        }
        release {
            isMinifyEnabled = false
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            applicationVariants.all {
                outputs.all {
                    (this as? com.android.build.gradle.internal.api.BaseVariantOutputImpl)
                        ?.outputFileName = "writhdeck-release.apk"
                }
            }
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions { jvmTarget = "17" }

    buildFeatures { compose = true }
}

dependencies {
    val composeBom = platform("androidx.compose:compose-bom:2024.09.03")
    implementation(composeBom)

    implementation("androidx.appcompat:appcompat:1.7.0")
    implementation("androidx.core:core-ktx:1.13.1")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.5")
    implementation("androidx.lifecycle:lifecycle-runtime-compose:2.8.5")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.8.5")
    implementation("androidx.activity:activity-compose:1.9.2")
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.material:material-icons-extended")
    implementation("androidx.navigation:navigation-compose:2.8.1")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1")

    debugImplementation("androidx.compose.ui:ui-tooling")
    debugImplementation("androidx.compose.ui:ui-test-manifest")
}

